// antdv 真渲染组件目录 story 生成器（G-A · 四类页面之二：71 组件族基础渲染 story）。
//
// 枚举路径（研究 §6 实抓裁定）：静态解析 node_modules 内
// ant-design-vue/es/components.js 的 export 行（4.2.6 无 exports 字段 → 深路径不受
// export map 限制）。该文件 71 条 export 行 = 71 个组件族（antdv 官方组件目录口径；
// 「71 组件」分母）——主组件（default as X）+ 同族子导出（AnchorLink/FormItem 等，
// 4.2.6 实抓共 138 具名导出）。version/theme/cssinjs/install 等非组件导出住在
// es/index.js 增量里、天然不在本文件（研究 §6），过滤面由此归零。
//
// 真渲染裁定：每族一个基础渲染 story（CSF3 render 形态 A：component options +
// template 字符串，官方模板原文形态，研究 §3），主组件 + 同族导出全部真实挂载；
// antdv 全局注册走 preview.ts 的 setup(app => app.use(Antd))（vue3-vite 框架页原文
// 钩子），story 另做局部注册双保险。
import { readFileSync } from "node:fs";
import { join } from "node:path";
import {
  ANTDV_COMPONENTS_JS,
  resetDir,
  writeFileEnsuringDir,
} from "./common.mjs";

/** 服务式 API 族（主组件不可作组件挂载）→ 触发式演示 story。 */
const SERVICE_API_COMPONENTS = new Set(["message", "notification"]);

/** 基础渲染时补默认 slot 文本的导出名（仅限裸挂载可呈现内容的叶子件——生成器数据，非逐个手写 story）。 */
const SLOT_TEXT_BY_NAME = new Map([
  ["Button", "按钮"],
  ["Tag", "标签"],
  ["CheckableTag", "可选中标签"],
  ["TypographyTitle", "标题"],
  ["TypographyParagraph", "文本段落"],
  ["TypographyText", "文本"],
  ["TypographyLink", "链接"],
  ["BreadcrumbItem", "面包屑"],
  ["MenuItem", "菜单项"],
  ["TabPane", "标签页"],
  ["TimelineItem", "时间线节点"],
]);

/**
 * 解析 antdv es/components.js 的组件族（文件序，确定性）。
 * 行形态（4.2.6 实抓，71 行）：`export { default as X, Y } from './x';`——
 * 首个具名导出 = 族主组件（antdv 默认导出语义），其余 = 同族子导出。
 */
export function parseAntdvComponentFamilies(componentsJsContent) {
  const families = [];
  const seenPrimary = new Set();
  const exportPattern = /^export\s*\{([^}]+)\}\s*from\s*'([^']+)';$/;
  for (const line of componentsJsContent.split("\n")) {
    const match = exportPattern.exec(line.trim());
    if (!match) continue;
    const names = match[1]
      .split(",")
      .map((token) => {
        const trimmed = token.trim();
        return trimmed.startsWith("default as ") ? trimmed.slice("default as ".length) : trimmed;
      });
    for (const name of names) {
      if (!/^[A-Za-z][A-Za-z0-9]*$/.test(name)) {
        throw new Error(`antdv components.js 出现非标识符导出名: ${JSON.stringify(name)}`);
      }
    }
    const primary = names[0];
    if (seenPrimary.has(primary)) {
      throw new Error(`antdv components.js 主导出名重复: ${primary}`);
    }
    seenPrimary.add(primary);
    families.push({ primary, secondary: names.slice(1), module: match[2] });
  }
  if (families.length === 0) {
    throw new Error("antdv components.js 解析出 0 个组件族——文件形态变化？");
  }
  return families;
}

/** 族内单个导出名的模板元素（slot 文本叶子件补默认内容，其余裸挂载）。 */
function templateElement(name) {
  const slotText = SLOT_TEXT_BY_NAME.get(name);
  return slotText ? `<${name}>${slotText}</${name}>` : `<${name} />`;
}

/** 单组件族 → CSF3 story 文件文本。 */
export function renderComponentStory(family) {
  const { primary, secondary } = family;
  const allNames = [primary, ...secondary];
  const importStatement = `import { ${allNames.join(", ")} } from 'ant-design-vue';`;
  const header = [
    `// GENERATED by packages/studio/scripts/lib/components.mjs —— 禁手改（重跑生成器覆盖）。`,
    `// 源：node_modules/ant-design-vue/es/components.js export 行（版本钉 4.2.6，族 ${family.module}）。`,
    `// NON-AUTHORITATIVE：画廊基础渲染呈现，权威语义以 catalog/seeds 锚定源为准（G-D：业务零出现）。`,
    `import type { Meta, StoryObj } from '@storybook/vue3';`,
    importStatement,
    ``,
  ];
  if (SERVICE_API_COMPONENTS.has(primary)) {
    // 服务式 API：真实调用演示（挂载的是触发按钮，点击调 message/notification）。
    return [
      ...header,
      `const meta = {`,
      `  title: 'AntDV 组件/${primary}',`,
      `  parameters: {`,
      `    docs: { description: { component: '${primary} 是服务式 API（非组件）——画廊以触发按钮做真实调用演示。' } },`,
      `  },`,
      `};`,
      `export default meta;`,
      ``,
      `export const Default: StoryObj = {`,
      `  render: () => ({`,
      `    setup() {`,
      `      const trigger = () => {`,
      `        ${primary}.info('POMaster 画廊演示：${primary} 服务式 API');`,
      `      };`,
      `      return { trigger };`,
      `    },`,
      `    template: '<div class="studio-demo"><button class="studio-demo-trigger" @click="trigger">触发 ${primary}（服务式 API）</button></div>',`,
      `  }),`,
      `};`,
      ``,
    ].join("\n");
  }
  const siblingNote =
    secondary.length > 0 ? ` 同族导出一并真渲染：${secondary.join("、")}。` : "";
  const componentsClause = `components: { ${allNames.join(", ")} },`;
  const template = `<div class="studio-demo">${allNames.map(templateElement).join("")}</div>`;
  return [
    ...header,
    `const meta = {`,
    `  title: 'AntDV 组件/${primary}',`,
    `  component: ${primary},`,
    `  parameters: {`,
    `    docs: { description: { component: 'ant-design-vue 4.2.6 基础渲染（画廊生成器产出）。${siblingNote}' } },`,
    `  },`,
    `} satisfies Meta<typeof ${primary}>;`,
    `export default meta;`,
    ``,
    `export const Default: StoryObj = {`,
    `  render: () => ({`,
    `    ${componentsClause}`,
    `    template: ${JSON.stringify(template)},`,
    `  }),`,
    `};`,
    ``,
  ].join("\n");
}

/** 生成全部组件族 story（返回 { count, files, families }；outDir 幂等清场重建）。 */
export function generateComponentStories(outDir, componentsJsPath = ANTDV_COMPONENTS_JS) {
  if (!outDir) throw new Error("generateComponentStories 需要显式 outDir（generate-all 注入）");
  const families = parseAntdvComponentFamilies(readFileSync(componentsJsPath, "utf8"));
  resetDir(outDir);
  const files = [];
  for (const family of families) {
    const target = join(outDir, `${family.primary}.stories.ts`);
    writeFileEnsuringDir(target, renderComponentStory(family));
    files.push(target);
  }
  return { count: files.length, files, families };
}
